/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";

export function CloudTest({ opacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud_test.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Plane001_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-0.787, 0, -5.259]}
        rotation={[-Math.PI / 2, 0, 0]}
        envMapIntensity={2}
      />
    </group>
  );
}

useGLTF.preload("./models/cloud_test.glb");
